package com.example.productschedule.bean

data class Lines(
    val devId: String,
    val devCode: String,
    val ProductType : String,
    val funcId: String,
    val dtId: String,
    val decType: String,
    val embossimglevel: String,
    val devWidth: String,
    val transmMode: String,
    val packageMode: String,
    val rollType: String,
    val MinGw: String,
    val MaxGw: String,
    val rollSpecs: String,
    val throughput: String,
    val unitMode: String,
    val devStatus: String,
    val remark: String,
    val actflag: String,
    val createDate: String,
    val createPsn: String,
    val updateDate: String,
    val updatePsn: String,
    val fstId: String,
    val MinProWith: String,
    val MaxProWith: String,

)
